version: "3.1"
services:
  memcached:
    image: "memcached:alpine"

  mailhog:
    image: "mailhog/mailhog:latest"
    ports:
      - "8001:8025"

  mysql:
    image: "mysql:8.0"
    working_dir: /application
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - "8002:3306"

  clickhouse:
    image: "yandex/clickhouse-server:latest"

  webserver:
    image: "nginx:alpine"
    working_dir: /application
    volumes:
      - ".:/application"
      - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8000:80"

  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /application
    volumes:
      - ".:/application"
      - "./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini"
